spring:
 application:
  name: spring-cloud-consumer

# 消费方端口号
server:
 port: 8081

# 指定服务注册地址
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8000/eureka/
   
# 设置Hystrix超时时间
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 5000
      
# 开启Hystrix熔断
feign:
 hystrix:
  enabled: true